apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/dk10ws/slcm-backend:647aaf52c0bd567ecdb5f293e50af8535fa9f237
          ports:
            - containerPort: 8000
