apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/dk10ws/slcm-backend:b172843b8bb6be82f8b71290f9aec92a2f7b66da
          ports:
            - containerPort: 8000
