apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/dk10ws/slcm-backend:ec930e1479654d425a12f47fe710c8555cb5bfad
          ports:
            - containerPort: 8000
