services:
  frontend:
    container_name: slcm-frontend
    image: ghcr.io/dk10ws/slcm-frontend:latest
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    container_name: slcm-backend
    image: ghcr.io/dk10ws/slcm-backend:latest
    ports:
      - 8000:8000
    restart: unless-stopped
