services:
  frontend:
    container_name: slcm-frontend
    build: frontend
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    container_name: slcm-backend
    build: backend
    ports:
      - 8000:8000
    restart: unless-stopped
