[project]
name = "betterslcm-backend"
version = "0.1.0"
description = "FastAPI application for SLCM Switch"
readme = "README.md"
authors = [
    { name = "Karan Parashar", email = "whyredfire@gmail.com" },
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "uvicorn>=0.52.3",
]

[dependency-groups]
dev = [
    "nox>=2026.8.10",
    "pyrefly>=1.2.0",
    "ruff>=0.16.3",
]

[tool.pyright]
# Pyright is only used for editors

# Pyright ReportCallIssue is incorrectly flagged on
# pydantic models and settings on defaults
reportCallIssue = false
