[project]
name = "betterslcm-backend"
version = "0.1.0"
description = "FastAPI application for SLCM Switch"
readme = "README.md"
authors = [
    { name = "Karan Parashar", email = "whyredfire@gmail.com" },
]
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi>=0.135.2",
    "httpx>=0.28.1",
    "uvicorn>=0.42.0",
]

[dependency-groups]
dev = [
    "nox>=2026.2.9",
    "pyrefly>=0.58.0",
    "ruff>=0.15.8",
]

[tool.pyright]
# Pyright is only used for editors

# Pyright ReportCallIssue is incorrectly flagged on
# pydantic models and settings on defaults
reportCallIssue = false
