apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/dk10ws/slcm-frontend:19d8ad1a88c7d6a53d1696383cd228477eb4a077
          ports:
            - containerPort: 8080
