apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/dk10ws/slcm-frontend:ec930e1479654d425a12f47fe710c8555cb5bfad
          ports:
            - containerPort: 8080
