// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVvwUJs-mnITQj1TsJfp29AyOcgABmXLw',
    appId: '1:20351027014:web:dae08df05b463406f6c747',
    messagingSenderId: '20351027014',
    projectId: 'mujslcm-93ace',
    authDomain: 'mujslcm-93ace.firebaseapp.com',
    databaseURL: 'https://mujslcm-93ace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mujslcm-93ace.firebasestorage.app',
    measurementId: 'G-T0KTYX3QR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpHUkh5X1xzjGX3N6nt2ZCwnOVPoddEuE',
    appId: '1:20351027014:android:7a10bd6ff55787eef6c747',
    messagingSenderId: '20351027014',
    projectId: 'mujslcm-93ace',
    databaseURL: 'https://mujslcm-93ace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mujslcm-93ace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7TgBbxOvGaLu5-Fe60dqHDtYIDtxSMkA',
    appId: '1:20351027014:ios:d71168fe82c20d4af6c747',
    messagingSenderId: '20351027014',
    projectId: 'mujslcm-93ace',
    databaseURL: 'https://mujslcm-93ace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mujslcm-93ace.firebasestorage.app',
    iosBundleId: 'com.example.mujslcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7TgBbxOvGaLu5-Fe60dqHDtYIDtxSMkA',
    appId: '1:20351027014:ios:d71168fe82c20d4af6c747',
    messagingSenderId: '20351027014',
    projectId: 'mujslcm-93ace',
    databaseURL: 'https://mujslcm-93ace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mujslcm-93ace.firebasestorage.app',
    iosBundleId: 'com.example.mujslcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVvwUJs-mnITQj1TsJfp29AyOcgABmXLw',
    appId: '1:20351027014:web:23f7e0d4a314d112f6c747',
    messagingSenderId: '20351027014',
    projectId: 'mujslcm-93ace',
    authDomain: 'mujslcm-93ace.firebaseapp.com',
    databaseURL: 'https://mujslcm-93ace-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mujslcm-93ace.firebasestorage.app',
    measurementId: 'G-GNPMWC0C82',
  );
}
